apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lemp
  name: lemp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lemp
  template:
    metadata:
      labels:
        app: lemp
    spec:
      containers:
      - image: nginx:1.28
        name: nginx
        env:
          - name: STAGE
            value: K8S
          - name: JOURS
            value: "10"
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: LEVEL
            valueFrom:
              configMapKeyRef:
                name: nginx-env
                key: NIVEAU
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                name: test
                key: PASSWD
        envFrom:
          - configMapRef:
              name: nginx-env
            prefix: bob_
        livenessProbe:
          httpGet:
            port: 80
            path: /index.html 
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: 80
            path: /index.html 
          periodSeconds: 5
          failureThreshold: 2
      - image: php:8.2-fpm
        name: php
