apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: stage-get-pod
  namespace: stage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-pod
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: stage
