apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-http
  name: hello-http
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-http
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-http
    spec:
      containers:
      - image: bob2606/hello-http:0.8.33
        name: hello-http
        resources: {}
status: {}

#  k create deployment test --image bob2606/hello-http:0.8.33 --replicas 2 --dry-run=client -o yaml > deployement.yaml